name: deploy to Email lambda
on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: Move node_modules to dist
        run: mv node_modules dist/node_modules
      - name: zip
        run: (cd dist && zip -r ../bundle.zip .)
       
      - name: deploy to AWS
        uses: appleboy/lambda-action@v0.1.3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws_region: us-east-1
          function_name: emailResponse
          zip_file: bundle.zip